modLoader="javafml" #mandatory
loaderVersion="[41,)" #mandatory
license="Apache License Version 2.0"

[[mods]] #mandatory
modId = "pigsteel" #mandatory
version = "${file.jarVersion}" #mandatory
logoFile = "pigsteel_icon.png" #optional
authors = "Uraneptus, DigitalPear_11, PeterGamesGR" #optional
credits = "Credits to DigitalPear_11 for the original fabric version of this mod" #optional
displayURL = "https://www.curseforge.com/minecraft/mc-mods/pigsteel-forge"
displayName = "Pigsteel Mod" #mandatory
description = '''
A mod that adds a nether counterpart to iron.
'''
[[dependencies.pigsteel]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[41.1,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.pigsteel]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,)"
    ordering="NONE"
    side="BOTH"

[modproperties.pigsteel]
    catalogueImageIcon= "pigsteel_icon.png"
