modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory
license="Apache License Version 2.0"

[[mods]] #mandatory
modId = "pigsteel" #mandatory
version = "${file.jarVersion}" #mandatory
logoFile = "pigsteel_icon.png" #optional
authors = "Uraneptus" #optional
credits = "Credits to DigitalPear for the original fabric version of this mod and to Tamakii, KingRolly for creating the textures" #optional
displayURL = "https://www.curseforge.com/minecraft/mc-mods/pigsteel-forge"
displayName = "Pigsteel Mod" #mandatory
description = '''
A mod that adds a nether counterpart to iron.
'''
[[dependencies.pigsteel]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[47.1,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.pigsteel]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"

[modproperties.pigsteel]
    catalogueImageIcon= "pigsteel_icon.png"
