modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="Apache License Version 2.0"

[[mods]] #mandatory
modId="pigsteel" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Pigsteel Mod" #mandatory
logoFile="icon.png" #optional
credits="Credits to DigitalPear_11 for the original fabric version of this mod" #optional
authors="Uraneptus, DigitalPear_11, PeterGamesGR" #optional
description='''
A mod that adds a nether counterpart to iron.
'''
[[dependencies.examplemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
