modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
logoFile="pigsteel_icon.png"
authors="${mod_authors}"
credits="Credits to DigitalPear for the original fabric version of this mod and to Tamakii & KingRolly for creating the textures"
displayURL="https://www.curseforge.com/minecraft/mc-mods/pigsteel-forge"
displayName="${mod_name}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[modproperties.pigsteel]
    catalogueImageIcon= "pigsteel_icon.png"
